<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Capítulo 5 QualityTools | Integración del Paquete QualityTools con Tidyverse</title>
<meta name="author" content="Miguel Flores">
<meta name="author" content="Andrea Barahona">
<meta name="author" content="Fabián Encarnación">
<meta name="author" content="Dario Quishpe">
<meta name="generator" content="bookdown 0.37 with bs4_book()">
<meta property="og:title" content="Capítulo 5 QualityTools | Integración del Paquete QualityTools con Tidyverse">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Capítulo 5 QualityTools | Integración del Paquete QualityTools con Tidyverse">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.6.0/transition.js"></script><script src="libs/bs3compat-0.6.0/tabs.js"></script><script src="libs/bs3compat-0.6.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<meta name="description" content="Este trabajo pretende dar una breve introducción a los métodos del paquete QualityTools. Este paquete se implementó con fines didácticos para servir como una “Caja de Herramientas” (Six-Sigma) y...">
<meta property="og:description" content="Este trabajo pretende dar una breve introducción a los métodos del paquete QualityTools. Este paquete se implementó con fines didácticos para servir como una “Caja de Herramientas” (Six-Sigma) y...">
<meta name="twitter:description" content="Este trabajo pretende dar una breve introducción a los métodos del paquete QualityTools. Este paquete se implementó con fines didácticos para servir como una “Caja de Herramientas” (Six-Sigma) y...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Integración del Paquete QualityTools con Tidyverse</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Preámbulo</a></li>
<li><a class="" href="poo-programaci%C3%B3n-orientada-a-objetos.html"><span class="header-section-number">2</span> (POO) Programación Orientada a Objetos</a></li>
<li><a class="" href="r6.html"><span class="header-section-number">3</span> R6</a></li>
<li><a class="" href="tidyquant.html"><span class="header-section-number">4</span> TidyQuant</a></li>
<li><a class="active" href="qualitytools.html"><span class="header-section-number">5</span> QualityTools</a></li>
<li><a class="" href="cambio-de-funciones.html"><span class="header-section-number">6</span> Cambio de Funciones</a></li>
<li><a class="" href="referencias.html">Referencias</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="qualitytools" class="section level1" number="5">
<h1>
<span class="header-section-number">Capítulo 5</span> QualityTools<a class="anchor" aria-label="anchor" href="#qualitytools"><i class="fas fa-link"></i></a>
</h1>
<div>
<img src="graficos/introduccion.png" width="120" align="right">
</div>
<p>Este trabajo pretende dar una breve introducción a los métodos del paquete <strong>QualityTools</strong>. Este paquete se implementó con fines didácticos para servir como una “Caja de Herramientas” (Six-Sigma) y contiene métodos asociados con el ciclo de resolución con la metodología de: “Definir, Medir, Analizar, Mejorar y Controlar” (con sus siglas en inglés DMAIC).</p>
<p>El uso de estos métodos se ilustran con ayuda de conjuntos de datos creados artificalmente, a continuación se explica, el objetivo de cada una de las fases de este ciclo:</p>
<ul>
<li><p><strong>Definir</strong>: Describir el problema y sus consecuencias (financieras), es la etapa fundamental para delimitar el problema. Los diagramas de flujo. Los diagramas de flujo de procesos identifican elementos cruciales del proceso (es decir, actividades), las técnicas de creatividad como Brainwriting y Brainstorming, así como la técnica SIPOC4, deberían conducir, dependiendo
del tamaño futuro del proyecto, a posiblemente una carta del proyecto.</p></li>
<li><p><strong>Medir</strong>: Elaborar un plan razonable para recopilar los datos requeridos y asegurarse de que los sistemas de medición sean capaces (es decir, ningún sesgo o sesgo conocido y la menor variación inmanente del sistema que
contribuya a las mediciones como sea posible). Dentro de esta fase se proporciona una descripción de la situación con la ayuda de índices de capacidad de proceso o de medición (MSA5 Tipo I) o un Gage R&amp;R (MSA Tipo II)</p></li>
<li><p><strong>Analizar</strong>: Intente encontrar las causas fundamentales del problema utilizando varios métodos estadísticos, como histogramas, regresión, correlación, identificación de distribución, análisis de varianza y gráficos multivariados.</p></li>
<li><p><strong>Mejorar</strong>: Utiliza experimentos diseñados, es decir, factoriales completos y fraccionarios, diseños de superficies de respuesta, diseños de mezclas, diseños de taguchi y el concepto de deseabilidad para encontrar
configuraciones o soluciones óptimas para un problema.</p></li>
<li><p><strong>Controlar</strong>: Una vez que se logró una mejora, es necesario asegurarla, lo que significa que se deben implementar acuerdos para garantizar el nivel de mejora. El uso de control estadístico de procesos (es decir, gráficos de control de calidad) se puede utilizar para monitorear el comportamiento de un proceso</p></li>
</ul>
<div id="fase-1-definir" class="section level2" number="5.1">
<h2>
<span class="header-section-number">5.1</span> Fase 1: Definir<a class="anchor" aria-label="anchor" href="#fase-1-definir"><i class="fas fa-link"></i></a>
</h2>
<p>La mayoría de las técnicas utilizadas en esta fase no están relacionadas con el uso sustancial de métodos estadísticos. Su objetivo es captar los conocimientos e ideas sobre el proceso involucrado, establecer un objetivo común y definir cómo cada parte contribuye a la solución.</p>
<p>Una técnica de visualización clásica que se utiliza en esta fase y está disponible en el paquete QualityTools es el <strong>Diagrama de Pareto</strong>, que nos ayuda a separar las pocas causas vitales de las muchas causas triviales.</p>
<p>Por ejemplo, en la causa más frecuente de un producto defectuoso, el diagrama de Pareto nos ayuda a visualizar cuánto contribuye una causa a un problema. Supongamos que una empresa está investigando unidades (productos) que no cumplen. 120 unidades fueron investigadas y se encontraron 6 tipos diferentes de defectos (datos cualitativos). Los defectos son denominados de A a F por fines prácticos.</p>
<div class="sourceCode" id="cb93"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">defectos</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"E"</span>,<span class="fl">62</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"B"</span>,<span class="fl">15</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"F"</span>,<span class="fl">3</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"A"</span>,<span class="fl">10</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"C"</span>,<span class="fl">20</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"D"</span>,<span class="fl">10</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu">paretoChart</span><span class="op">(</span><span class="va">defectos</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-79-1.png" width="768" style="display: block; margin: auto;"></div>
<p>En este diagrama de Pareto podría transmitir el mensaje de que para resolver el <span class="math inline">\(68\%\)</span> de los problemas, el <span class="math inline">\(33 \%\)</span> de las causas (menos vitales) necesitan ser objeto de investigación.</p>
<p>Además de este uso, los diagramas de Pareto también se utilizan para visualizar los tamaños de efectos de los diferentes factores para los experimentos diseñados, a continución se muestra un ejemplo de una gráfica de errores de medición.</p>
<div class="inline-figure"><img src="graficos/erroresMedida.png" width="700"></div>
</div>
<div id="fase-2-medir" class="section level2" number="5.2">
<h2>
<span class="header-section-number">5.2</span> Fase 2: Medir<a class="anchor" aria-label="anchor" href="#fase-2-medir"><i class="fas fa-link"></i></a>
</h2>
<p>La recopilación de datos implica el uso de sistemas de medición a menudo denominados calibres. Para hacer una declaración sobre la calidad, el sistema de medición utilizado debe ser validado, y por lo tanto la variación para repetidas mediciones de la misma unidad debe ser tolerable, y por supuesto, debe depender del número de categorías distintivas qque necesita para poder identificar y caracterizar el producto.</p>
<p>Esta cantidad tolerable de variación para un sistema de medición se relaciona directamente al rango de tolerancia de las características de un producto. La capacidad de un sistema de mediciones es crucial para cualquier conclusión basada en datos y está directamente relacionada con los costos que implican los errores tipo I y tipo II.</p>
<div id="capacidad-de-calibre---msa-tipo-i" class="section level3" number="5.2.1">
<h3>
<span class="header-section-number">5.2.1</span> Capacidad de calibre - MSA Tipo I<a class="anchor" aria-label="anchor" href="#capacidad-de-calibre---msa-tipo-i"><i class="fas fa-link"></i></a>
</h3>
<p>Supongamos que un ingeniero quiere comprobar la capacidad de un dispositivo de medición óptico. Una unidad con característica conocida (<span class="math inline">\(x_m = 10.033mm\)</span>) se mide repetidamente <span class="math inline">\(n=25\)</span> veces. De los valores de medición se obtiene la media <span class="math inline">\(\bar{x_g}\)</span> y la desviación estándar <span class="math inline">\(s_g\)</span>.</p>
<p>Basicamente el cálculo de un índice de capacidad comprende dos pasos: primero se calcula una fracción del ancho de toletancia (es decir, <span class="math inline">\(USL - LSL\)</span>), la fracción típicamente se relaciona a <span class="math inline">\(0.2\)</span>. En un segundo paso esta fracción se relaciona con una medida de la dispersión del proceso (es decir, el rango en el que el <span class="math inline">\(95,5\%\)</span>, o el <span class="math inline">\(99.73\%\)</span> de las características de un proceso son esperados).</p>
<p>Para valores de medición distribuidos normalmentem esto se relaciona con <span class="math inline">\(k = 2 \sigma_g\)</span> y <span class="math inline">\(k = 3 \sigma_g\)</span> calculados a partir de llos valores de medición; y para datos que no están distribuidos normalmente, se pueden tomar los cuantiles correspondientes. Si no hay sesgo, este cálculo representa el índice de capacidad <span class="math inline">\(c_g\)</span> y refleja la verdadera capacidad del dispositivo de medición.</p>
<p><span class="math display">\[
\begin{aligned}
c_g &amp;= \frac{0.2 \cdot (USL - LSL)}{6 \cdot s_g} \\
    &amp;= \frac{0.2 \cdot (USL - LSL)}{X_{0.99865} - X_{0.00135}}  
\end{aligned}
\]</span></p>
<p>Sin embargo, si hay un sesgom se tiene en cuenta al restarlo del numerador, en este caso, <span class="math inline">\(c_g\)</span> refleja solo la capacidad potencial (es decir, la capacidad si se corrige el sesgo), y <span class="math inline">\(c_{gk}\)</span> es un estimador de la capacidad real. El sesgo se calcula como la diferencia entre la característica conocida <span class="math inline">\(x_m\)</span> y la media de los valoes de medición <span class="math inline">\(x_g\)</span>.</p>
<p><span class="math display">\[
c_{gk} = \frac{0.1 \cdot (USL - LSL) - |x_m - x_g|}{3 \cdot s_g}
\]</span></p>
<p>Determinar si el sesgo se debe al azar o no, se puede hacer con la ayuda de una prueba t que tiene la forma general siguiente:</p>
<p><span class="math display">\[
t = \frac{diferencia de medias}{error estandar de la diferencia} = \frac{Dif}{s_{Dif}/\sqrt{n}}
\]</span></p>
<p>Además del sesgo y la desviación estándar, es importante comprobar el diagrama de ejecución de los valores de medición. Usando el paquete QualityTools, todo esto se logra fácilmente usando el método <code>cg</code>, su resultado se muestra a continuación:</p>
<div class="sourceCode" id="cb94"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.r-qualitytools.org">qualityTools</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span> <span class="op">(</span> <span class="fl">9.991</span>, <span class="fl">10.013</span>, <span class="fl">10.001</span>, <span class="fl">10.007</span>, <span class="fl">10.010</span>, <span class="fl">10.013</span>, <span class="fl">10.008</span>, <span class="fl">10.017</span>, <span class="fl">10.005</span>, <span class="fl">10.005</span>, <span class="fl">10.002</span>,</span>
<span>        <span class="fl">10.017</span>, <span class="fl">10.005</span>, <span class="fl">10.002</span>, <span class="fl">9.996</span>, <span class="fl">10.011</span>, <span class="fl">10.009</span> , <span class="fl">10.006</span>, <span class="fl">10.008</span>, <span class="fl">10.003</span>, <span class="fl">10.002</span>, <span class="fl">10.006</span>, </span>
<span>        <span class="fl">10.010</span>, <span class="fl">9.992</span>, <span class="fl">10.013</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/cg.html">cg</a></span><span class="op">(</span><span class="va">x</span>, target <span class="op">=</span> <span class="fl">10.003</span>, tolerance <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">9.903</span>, <span class="fl">10.103</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-80-1.png" width="768" style="display: block; margin: auto;"></div>
</div>
<div id="repetibilidad-y-reproducibidad-del-calibre---msa-tipo-ii" class="section level3" number="5.2.2">
<h3>
<span class="header-section-number">5.2.2</span> Repetibilidad y reproducibidad del calibre - MSA Tipo II<a class="anchor" aria-label="anchor" href="#repetibilidad-y-reproducibidad-del-calibre---msa-tipo-ii"><i class="fas fa-link"></i></a>
</h3>
<p>Un procedimineto común aplicado en la industria es realizar un análisis <em>Gage R&amp;R</em> para evaluar la repetibilidad y reproducibilidad de un sistema de medición (‘R&amp;R’ significa repetibilidad y reproducibilidad).</p>
<p>La repetibilidad se refiere a la precisión de un sistema de medición, es decir, a la desviación estándar de mediciones posteriores de la misma unidad. miestras que reproducibilidad es la parte de la varianza general que modela el efecto de diferentes, por ejemplo, operadores que realizan mediciones en la misma unidad y una posible interacción entre diferentes operadores y piezas medidas dentro de este “Gage R&amp;R”, el modelo general está dado por:</p>
<p><span class="math display">\[
\sigma^2_{total} = \sigma^2_{Piezas} + \sigma^2_{Operadores}  + \sigma^2_{Piezas \times Operador} + \sigma^2_{Error}
\]</span></p>
<p>Donde:</p>
<ul>
<li><p><span class="math inline">\(\sigma^2_{Piezas}\)</span>: modela la variación entre diferentes unidades de un mismo proceso, por lo tanto, <span class="math inline">\(\sigma\)</span> es una estimación de la variabilidad inherente del proceso.</p></li>
<li><p>$^2_{Operador} + ^2_{Piezas Operador} $: modela la reproducibilidad.</p></li>
<li><p><span class="math inline">\(\sigma^2_{Error}\)</span>: modela la repetibilidad.</p></li>
</ul>
<p>Ahora, supongamos que 3 operadores elegidos al azar midieron 10 unidades elegidas al azar. Cada operador midió cada unidad dos veces en un orden elegido al azar y las unidades no puedes distingirse entre si.</p>
<p>El <em>Diseño R&amp;R del Calibre</em> correspondiente se puede crear utilizando el método <code>gageRRDesign</code> del paquete QualityTools, y las medidas se asignan a este diseño utilizando el método de respuesta, dados por <code>gageRR</code> y <code>plot</code>.</p>
<div class="sourceCode" id="cb95"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.r-qualitytools.org">qualityTools</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Crear un diseño R&amp;R de Calibre</span></span>
<span><span class="va">dis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/gageRRDesign.html">gageRRDesign</a></span><span class="op">(</span>Operators <span class="op">=</span> <span class="fl">3</span>, Parts <span class="op">=</span> <span class="fl">10</span>, Measurements <span class="op">=</span> <span class="fl">2</span>, randomize <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Establecemos las respuestas de medición</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/response-methods.html">response</a></span><span class="op">(</span><span class="va">dis</span><span class="op">)</span> <span class="op">&lt;-</span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">23</span>, <span class="fl">22</span>, <span class="fl">22</span>, <span class="fl">22</span>, <span class="fl">22</span>, <span class="fl">25</span>, <span class="fl">23</span>, <span class="fl">22</span>, <span class="fl">23</span>, <span class="fl">22</span>, <span class="fl">20</span>, <span class="fl">22</span>, <span class="fl">22</span>, <span class="fl">22</span>, <span class="fl">24</span>, <span class="fl">25</span>, <span class="fl">27</span>, <span class="fl">28</span>, <span class="fl">23</span>, <span class="fl">24</span>, <span class="fl">23</span>, <span class="fl">24</span>, <span class="fl">24</span>, <span class="fl">22</span>, <span class="fl">22</span>, <span class="fl">22</span>, <span class="fl">24</span>, <span class="fl">23</span>, <span class="fl">22</span>, <span class="fl">24</span>, <span class="fl">20</span>, <span class="fl">20</span>, <span class="fl">25</span>, <span class="fl">24</span>, <span class="fl">22</span>, <span class="fl">24</span>, <span class="fl">21</span>, <span class="fl">20</span>, <span class="fl">21</span>, <span class="fl">22</span>, <span class="fl">21</span>, <span class="fl">22</span>, <span class="fl">21</span>, <span class="fl">21</span>, <span class="fl">24</span>, <span class="fl">27</span>,  <span class="fl">25</span>, <span class="fl">27</span>, <span class="fl">23</span>, <span class="fl">22</span>, <span class="fl">25</span>, <span class="fl">23</span>, <span class="fl">23</span>, <span class="fl">22</span>, <span class="fl">22</span>, <span class="fl">23</span>, <span class="fl">25</span>, <span class="fl">21</span>, <span class="fl">24</span>, <span class="fl">23</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Realizamos Gage R&amp;R</span></span>
<span><span class="va">gdo</span> <span class="op">&lt;-</span> <span class="fu">gageRR_abc</span><span class="op">(</span><span class="va">dis</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## AnOVa Table -  crossed Design
##               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Operator       2  20.63  10.317   8.597  0.00112 ** 
## Part           9 107.07  11.896   9.914 7.31e-07 ***
## Operator:Part 18  22.03   1.224   1.020  0.46732    
## Residuals     30  36.00   1.200                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## ----------
## AnOVa Table Without Interaction -  crossed Design
##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Operator     2  20.63  10.317   8.533 0.000675 ***
## Part         9 107.07  11.896   9.840 2.39e-08 ***
## Residuals   48  58.03   1.209                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## ----------
## 
## Gage R&amp;R
##                  VarComp VarCompContrib Stdev StudyVar StudyVarContrib
## totalRR            1.664          0.483 1.290     7.74           0.695
##  repeatability     1.209          0.351 1.100     6.60           0.592
##  reproducibility   0.455          0.132 0.675     4.05           0.364
##    Operator        0.455          0.132 0.675     4.05           0.364
##    Operator:Part   0.000          0.000 0.000     0.00           0.000
## Part to Part       1.781          0.517 1.335     8.01           0.719
## totalVar           3.446          1.000 1.856    11.14           1.000
## 
## ---
##  * Contrib equals Contribution in %
##  **Number of Distinct Categories (truncated signal-to-noise-ratio) = 1</code></pre>
<div class="sourceCode" id="cb97"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Visualización de Gage R&amp;R</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">gdo</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-83-1.png" width="672" style="display: block; margin: auto;"></div>
<p>El diagrama de barras ofrece una representación visual de los componentes de la varianza. <code>totalRR</code> representa la repetibilidad y reproducibilidad totales. El <span class="math inline">\(48\%\)</span> de la variación se debe al <span class="math inline">\(35\%\)</span> de <em>repitibilidad</em>, es decir, variación del propio calibre, y al <span class="math inline">\(13\%\)</span> de reproducibilidad, es decir, efecto del operador y la interación entre el operador y la pieza.</p>
<p>Se puede ver en la tabla Anova que no existe interacción entre piezas y operadores. El <span class="math inline">\(52\%\)</span> de la variación (columna <strong>VarCompContrib</strong>) se debe a diferencias entre las partes tomadas del proceso (variación inherente), que se puede ver en el gráfico <strong>Measurement by Part</strong>. La variación de las mediciones tomadas por un operador es aproximadamente igual para los tres operadores (<strong>Measurement by Operator</strong>), aunque el operador C parece producir valores que la mayoría de las veces son mayores que los valores de los otros operadores (<strong>Interaction Operator: Part</strong>).</p>
<p>Además de esta interpretación de los resultados, en la industria se utilizan valores críticos para <strong>totalRR</strong>, también denominado en la industria como “GRR”. Sin embargo, un sistema de medición nunca debe juzgarse únicamente por sus valores críticos.</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="58%">
<col width="41%">
</colgroup>
<thead><tr class="header">
<th>Contribución total RR</th>
<th>Capacidad</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>≤ 0.1</td>
<td>Adecuada</td>
</tr>
<tr class="even">
<td>&lt; 0.1 y &lt; 0.3</td>
<td>Adecuada con limitaciones dependiendo de las circunstancias</td>
</tr>
<tr class="odd">
<td>≥ 0.3</td>
<td>No adecuada</td>
</tr>
</tbody>
</table></div>
<ul>
<li><p><strong>Verificación de interacción: </strong> El gráfico de interacción proporciona una verificación visual de posibles interacciones entre el Operador y la Pieza. Para cada operador se muestra el valor medio de la
medición en función del número de pieza. Las líneas cruzadas indican que los operadores están asignando lecturas diferentes a idénticas dependiendo de la combinación de Operador y Pieza.
Diferentes lecturas significan, en el caso de una interacción entre Operador y Pieza, que en promedio a veces se asignan valores más pequeños o más grandes dependiendo de la combinación de Operador y Pieza. En este caso, las líneas prácticamente no se cruzan, pero el operador C parece asignar sistemáticamente lecturas mayores a las piezas que sus colegas.</p></li>
<li><p><strong>Operadores:</strong> Para comprobar si hay un efecto dependiente del operador, las mediciones se trazan agrupadas por operadores en forma de diagramas de caja. Los diagramas de caja que difieren en tamaño o ubicación pueden indicar, por ejemplo, posibles procedimientos diferentes dentro del proceso de medición, que luego conducen a una diferencia sistemática en las lecturas. En nuestro ejemplo se podría discutir un posible efecto para el operador C que también está respaldado por el gráfico de interacción.</p></li>
<li><p><strong>Variación inherente del proceso:</strong> Dentro de este gráfico las mediciones están agrupadas por operador. Gracias a las mediciones repetidas realizadas por diferentes operadores por pieza, se obtiene
una idea del proceso. Una línea que conecta la media de las mediciones de cada parte proporciona una idea de la variación inherente del proceso. Cada pieza se mide el número de operadores multiplicado por el número de mediciones por pieza.</p></li>
<li><p><strong>Componentes de Variación:</strong> Para comprender el resultado de un estudio de Gage R&amp;R se debe hacer referencia a la fórmula presentada al inicio de esta sección. El componente de varianza <code>totalRR</code> (columna <code>VarComp</code>) representa la repetibilidad y reproducibilidad total. Dado que las varianzas simplemente se suman, se tiene que <span class="math inline">\(1.664\)</span> es la suma de <span class="math inline">\(1.209\)</span> (repetibilidad dada por <span class="math inline">\(\sigma^2_{Error}\)</span>) y <span class="math inline">\(0.455\)</span> (reproducibilidad) que es la suma de Operador (<span class="math inline">\(\sigma^2_{Operador}\)</span>) y Operador:Parte (<span class="math inline">\(\sigma^2_{Partes \times Operador}\)</span>).</p></li>
</ul>
<p>Como no hay interacción, la reproducibilidad asciende a <span class="math inline">\(0.455\)</span>. <em>Parte a Parte</em> asciende a <span class="math inline">\(1.781\)</span>. Junto con el total de repetibilidad y reproducibilidad, esto da <span class="math inline">\(\sigma^2_{Total} = 3.446\)</span>.</p>
</div>
</div>
<div id="fase-3-analizar" class="section level2" number="5.3">
<h2>
<span class="header-section-number">5.3</span> Fase 3: Analizar<a class="anchor" aria-label="anchor" href="#fase-3-analizar"><i class="fas fa-link"></i></a>
</h2>
<div id="capacidad-del-proceso" class="section level3" number="5.3.1">
<h3>
<span class="header-section-number">5.3.1</span> Capacidad del Proceso<a class="anchor" aria-label="anchor" href="#capacidad-del-proceso"><i class="fas fa-link"></i></a>
</h3>
<p>Además de la capacidad de un sistema de medición, a menudo la capacidad de un proceso es de interés o necesidad que debe evaluarse, por ejemplo, como parte de una relación entre proveedor y cliente en la industria.</p>
<p>Los índices de capacidad del proceso básicamente indican cuánto del rango de tolerancia está siendo utilizado por la variación debida a causas comunes del proceso considerado. Utilizando estas técnicas, se puede determinar cuántas unidades (por ejemplo, productos) se espera que caigan fuera del rango de tolerancia, es decir, defectuoso con respecto a los requisitos determinados. También proporciona información sobre dónde centrar el proceso si el desplazamiento es posible y significativo en términos de costos.</p>
<p><span class="math display">\[
c_p = \frac{USL - LSL}{Q_{0.99865} - Q_{0.00135}}
\]</span></p>
<p><span class="math display">\[
c_{pkL} = \frac{Q_{0.5} - LSL}{Q_{0.5} - Q_{0.00135}}
\]</span>
<span class="math display">\[
c_{pkU} = \frac{USL - Q_{0.5}}{Q_{0.99865} - Q_{0.5}}
\]</span>
* <span class="math inline">\(c_p\)</span>: Es la capacidad potencial del proceso que podría lograrse si el proceso se pudiera centrar dentro de los límites de especificación.</p>
<ul>
<li>
<span class="math inline">\(c_{pk}\)</span>: Es la capacidad real del proceso que incorpora la ubicación de la distribución (es decir, el centro) de la característica dentro de los límites de especificación.</li>
</ul>
<p>Para límites de especificación unilaterales, existen <span class="math inline">\(c_{pkL}\)</span> y <span class="math inline">\(c_{pkU}\)</span>, siendo <span class="math inline">\(c_{pk}\)</span> igual al índice de capacidad más pequeño. Como se puede imaginar, además de la ubicación de la distribución de la característica, la forma de la distribución también es relevante. Evaluar el ajuste de una distribución específica para datos dados se puede hacer a través de gráficos de probabilidad (ppPlot) y gráficos de cuantiles-cuantiles (qqPlot), así como métodos de prueba formales como la Prueba de Anderson-Darling.</p>
<p>Las capacidades del proceso pueden calcularse con el método <strong>pcr</strong> del paquete qualityTools. El método pcr traza un histograma de los datos, la distribución ajustada y devuelve los índices de capacidad junto con los parámetros estimados de la distribución, una Prueba de Anderson-Darling para la distribución especificada y el correspondiente QQ-Plot.</p>
<p><strong>Ejemplos:</strong></p>
<ol style="list-style-type: decimal">
<li>Distribución Normal</li>
</ol>
<div class="sourceCode" id="cb98"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">datos</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">20</span>, mean <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/pcr.html">pcr</a></span><span class="op">(</span><span class="va">datos</span>, <span class="st">"normal"</span>, lsl <span class="op">=</span> <span class="fl">17</span>, usl <span class="op">=</span> <span class="fl">23</span><span class="op">)</span></span>
<span><span class="co">## Error in round(x$statistic, 4): non-numeric argument to mathematical function</span></span></code></pre></div>
<div class="inline-figure"><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-85-1.png" width="672" style="display: block; margin: auto;"></div>
<ol start="2" style="list-style-type: decimal">
<li>Distribución Weibull</li>
</ol>
<div class="sourceCode" id="cb99"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">weib</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Weibull.html">rweibull</a></span><span class="op">(</span><span class="fl">20</span>, shape <span class="op">=</span> <span class="fl">2</span>, scale <span class="op">=</span> <span class="fl">8</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/pcr.html">pcr</a></span><span class="op">(</span><span class="va">weib</span>, <span class="st">"weibull"</span>, usl <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span>
<span><span class="co">## Error in round(x$statistic, 4): non-numeric argument to mathematical function</span></span></code></pre></div>
<div class="inline-figure"><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-86-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Junto con la representación gráfica se presenta un Test de Anderson Darling y se devuelve la distribución</p>
<div class="inline-figure"><img src="graficos/AndersonDarling.png"></div>
<p>Los gráficos QQ-plot pueden obtenerse a partir del paquete QualityTools, de la siguiente forma:</p>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/qqPlot.html">qqPlot</a></span><span class="op">(</span><span class="va">weib</span>, <span class="st">"weibull"</span><span class="op">)</span>; <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/qqPlot.html">qqPlot</a></span><span class="op">(</span><span class="va">datos</span>, <span class="st">"normal"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-87-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Y los gráficos de probabilidad se pueden calcular con la función ppPlot del mismo paquete, de la siguiente manera:</p>
<div class="sourceCode" id="cb101"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/ppPlot.html">ppPlot</a></span><span class="op">(</span><span class="va">weib</span>, <span class="st">"weibull"</span><span class="op">)</span>; <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/ppPlot.html">ppPlot</a></span><span class="op">(</span><span class="va">datos</span>, <span class="st">"normal"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-88-1.png" width="672" style="display: block; margin: auto;"></div>
</div>
</div>
<div id="fase-4-mejorar" class="section level2" number="5.4">
<h2>
<span class="header-section-number">5.4</span> Fase 4: Mejorar<a class="anchor" aria-label="anchor" href="#fase-4-mejorar"><i class="fas fa-link"></i></a>
</h2>
<div id="diseños-factoriales-2k" class="section level3" number="5.4.1">
<h3>
<span class="header-section-number">5.4.1</span> Diseños factoriales <span class="math inline">\(2^{k}\)</span><a class="anchor" aria-label="anchor" href="#dise%C3%B1os-factoriales-2k"><i class="fas fa-link"></i></a>
</h3>
<p>El método <code>facDesign</code> diseña un modelo de <em>k</em> factores y 2 combinaciones por factor, el cual es llamado <span class="math inline">\(2^k\)</span>.</p>
<p>Supondremos un ejemplo de un proceso que tiene 5 factores A, B, C, D y E, de los cuales tres se consideran relevantes para el rendimiento del proceso (A, B y C).</p>
<div class="sourceCode" id="cb102"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">dfac</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/facDesign.html">facDesign</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">3</span>, centerCube <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">dfac</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Facto 1'</span>, <span class="st">'Factor 2'</span>, <span class="st">'Factor 3'</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/lows-methods.html">lows</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">80</span>,<span class="fl">120</span>,<span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/highs-methods.html">highs</a></span><span class="op">(</span><span class="va">fdo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">120</span>,<span class="fl">140</span>,<span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dfac</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/dfac.png" width="260"></div>
<p>El proceso se simula con el método <code>simProc</code>:</p>
<div class="sourceCode" id="cb103"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#Primeros valores</span></span>
<span><span class="va">rend</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span>x1<span class="op">=</span><span class="fl">120</span>,x2<span class="op">=</span><span class="fl">140</span>,x3<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="co">#valores completos</span></span>
<span><span class="va">rend</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">120</span>,<span class="fl">140</span>,<span class="fl">1</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">80</span>,<span class="fl">140</span>,<span class="fl">1</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">120</span>,<span class="fl">140</span>,<span class="fl">2</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">120</span>,<span class="fl">120</span>,<span class="fl">1</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">90</span>,<span class="fl">130</span>,<span class="fl">1.5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">90</span>,<span class="fl">130</span>,<span class="fl">1.5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">80</span>,<span class="fl">120</span>,<span class="fl">2</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">90</span>,<span class="fl">130</span>,<span class="fl">1.5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">90</span>,<span class="fl">130</span>,<span class="fl">1.5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">120</span>,<span class="fl">120</span>,<span class="fl">2</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">80</span>,<span class="fl">140</span>,<span class="fl">2</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">80</span>,<span class="fl">120</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>Se asigna el rendimiento al diseño factorial:</p>
<div class="sourceCode" id="cb104"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/response-methods.html">response</a></span><span class="op">(</span><span class="va">dfac</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">rend</span></span></code></pre></div>
<p>Para el análisis del diseño se puede usar los métodos <code>effectPlot</code>, <code>interactionPlot</code>, <code>lm</code>, <code>wirePlot</code>, <code>contourPlot</code>.</p>
<div class="sourceCode" id="cb105"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/effectPlot.html">effectPlot</a></span><span class="op">(</span><span class="va">dfac</span>, classic <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div style="text-align:center">
<div class="inline-figure"><img src="graficos/effectplot.png" width="500"></div>
</div>
<div class="sourceCode" id="cb106"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/interactionPlot.html">interactionPlot</a></span><span class="op">(</span><span class="va">dfac</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/interactionplot.png" width="500"></div>
<p>Se puede usar el método de R <code>lm</code>, vemos a continuación:</p>
<div class="sourceCode" id="cb107"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">rend</span> <span class="op">~</span> <span class="va">A</span><span class="op">*</span><span class="va">B</span><span class="op">*</span><span class="va">C</span>, data<span class="op">=</span><span class="va">dfac</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m1</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/lmdfac.png" width="600"></div>
<p>Se puede que ver que A, B y AB son significativos.</p>
<p>También se puede obtener dos gráficas mediante <code>paretoPlot</code> y <code>normalPlot</code> del mismo paquete qualityTools.</p>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/paretoPlot.html">paretoPlot</a></span><span class="op">(</span><span class="va">dfac</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/normalPlot.html">normalPlot</a></span><span class="op">(</span><span class="va">dfac</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/dfac2plots.png" width="700"></div>
<p>La relación entre el factor A y el B se puede visualizar mediante una representación 3D mediante <code>wirePlot</code> y <code>contourPlot</code></p>
<div class="sourceCode" id="cb109"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/wirePlot.html">wirePlot</a></span><span class="op">(</span><span class="va">A</span>,<span class="va">B</span>,<span class="va">rend</span>,data<span class="op">=</span><span class="va">dfac</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/contourPlot.html">contourPlot</a></span><span class="op">(</span><span class="va">A</span>,<span class="va">B</span>,<span class="va">rend</span>,data<span class="op">=</span><span class="va">dfac</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/dfac3d.png" width="700"></div>
</div>
<div id="diseños-factoriales-fraccionarios-2k-p" class="section level3" number="5.4.2">
<h3>
<span class="header-section-number">5.4.2</span> Diseños factoriales fraccionarios <span class="math inline">\(2^{k-p}\)</span><a class="anchor" aria-label="anchor" href="#dise%C3%B1os-factoriales-fraccionarios-2k-p"><i class="fas fa-link"></i></a>
</h3>
<p>Este diseño tiene <span class="math inline">\(k\)</span> factores y se prueba en <span class="math inline">\(2k-p\)</span> ejecuciones, por ejemplo para un diseño <span class="math inline">\(2^{5-1}\)</span> se prueban cinco factores en 24 ejecuciones.</p>
<p>Para realizar esto se utiliza el método <code>fracDesign</code>, vamos a realizar el ejemplo de un diseño <span class="math inline">\(2^{3-1}\)</span>, para ello se debe utilizar el argumento <code>gen='C=AB'</code>, lo cual quiere decir que el efecto de C es equivalente al de AB:</p>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dfacfrac</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/fracDesign.html">fracDesign</a></span><span class="op">(</span>k<span class="op">=</span><span class="fl">3</span>,gen<span class="op">=</span><span class="st">'C=AB'</span>,centerCube <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span></code></pre></div>
<p>Se puede obtener información específica del diseño mediante <code>summary</code>:</p>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dfacfrac</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/fracdfac.png" width="270"></div>
<p>Vemos que en el modelo se muestra que <code>I=ABC</code> y por lo tanto se cumplen las siguientes reglas:</p>
<p><span class="math display">\[\begin{align}
I\times A&amp;=A\\
A\times A&amp;=I\\
A\times B&amp;=B\times A
\end{align}\]</span></p>
<p>Para encontrar todos los efectos equivalentes se puede usar los comandos:</p>
<div class="sourceCode" id="cb112"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/aliasTable.html">aliasTable</a></span><span class="op">(</span><span class="va">dfacfrac</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/aliastabledf.png" width="130"></div>
<div class="sourceCode" id="cb113"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/confounds.html">confounds</a></span><span class="op">(</span><span class="va">dfacfrac</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/confoundsdf.png" width="270"></div>
<p>Estos diseños se pueden generar asignando los generadores apropiados, el cual se puede elegir entre tabla predefinidas usando el método <code>fracChoose</code> y seleccionando el diseño deseado:</p>
<div class="sourceCode" id="cb114"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/fracChoose.html">fracChoose</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/dfchoose.png" width="700"></div>
</div>
<div id="diseños-replicados-y-puntos-centrales" class="section level3" number="5.4.3">
<h3>
<span class="header-section-number">5.4.3</span> Diseños replicados y puntos centrales<a class="anchor" aria-label="anchor" href="#dise%C3%B1os-replicados-y-puntos-centrales"><i class="fas fa-link"></i></a>
</h3>
<p>Se puede crear un diseño replicado con puntos centrales adicionales usando <code>replicates</code> y <code>centerCube</code>:</p>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dfac1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/facDesign.html">facDesign</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">3</span>, centerCube <span class="op">=</span> <span class="fl">2</span>, replicates <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="respuestas-múltiples" class="section level3" number="5.4.4">
<h3>
<span class="header-section-number">5.4.4</span> Respuestas múltiples<a class="anchor" aria-label="anchor" href="#respuestas-m%C3%BAltiples"><i class="fas fa-link"></i></a>
</h3>
<p>Se puede agregar vectores de respuesta al diseño con el método <code>response</code>. Por ejemplo, se crea una segunda respuesta <code>y2</code> que se llena con números aleatorios y se agrega al objeto creado.</p>
<div class="sourceCode" id="cb116"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">y2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">12</span>,mean<span class="op">=</span><span class="fl">120</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/response-methods.html">response</a></span><span class="op">(</span><span class="va">dfac</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">yield</span>,<span class="va">y2</span><span class="op">)</span></span></code></pre></div>
<p>Se puede visualizar en 3D con los métodos <code>wirePlot</code> y <code>contourPlot</code> especificando con <code>form</code>:</p>
<div class="sourceCode" id="cb117"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mforw <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/wirePlot.html">wirePlot</a></span><span class="op">(</span><span class="va">A</span>, <span class="va">B</span>, <span class="va">yield</span>, data <span class="op">=</span> <span class="va">dfac</span>, form <span class="op">=</span> <span class="st">"yield~A+B+C+A*B"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/contourPlot.html">contourPlot</a></span><span class="op">(</span><span class="va">A</span>, <span class="va">B</span>, <span class="va">y2</span>, data <span class="op">=</span> <span class="va">fdo</span>, form <span class="op">=</span> <span class="st">"y2~A+B+C+A*B"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/multidfac1.png" width="700"></div>
<p>Se puede crear los gráficos con el tercer factor C en -1 y <span class="math inline">\(C=1\)</span>, de la forma:</p>
<div class="sourceCode" id="cb118"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/wirePlot.html">wirePlot</a></span><span class="op">(</span><span class="va">A</span>, <span class="va">B</span>, <span class="va">y2</span>, data <span class="op">=</span> <span class="va">dfrac</span>, factors <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>C<span class="op">=</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span>, form <span class="op">=</span> <span class="st">"y2~A*B*C"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/wirePlot.html">wirePlot</a></span><span class="op">(</span><span class="va">A</span>, <span class="va">B</span>, <span class="va">y2</span>, data <span class="op">=</span> <span class="va">dfrac</span>, factors <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>C<span class="op">=</span><span class="fl">1</span><span class="op">)</span>, form <span class="op">=</span> <span class="st">"y2∼A∗B∗C"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/multidfac2.png" width="700"></div>
<p>Si no se proporciona ninguna fórmula explícitamente, los métodos predeterminados son el ajuste completo o el que está almacenado en el objeto de diseño factorial. El almacenamiento del ajusto se puede realizar con el método <code>fits</code> y se utiliza cuando se trabaja con más de una respuesta. Además, se utiliza <code>lm</code> para analizar el diseño factorial fraccionario.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="qualitytools.html#cb119-1" tabindex="-1"></a><span class="fu">fits</span>(fdo) <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield∼A<span class="sc">+</span>B, <span class="at">data =</span> fdo)</span>
<span id="cb119-2"><a href="qualitytools.html#cb119-2" tabindex="-1"></a><span class="fu">fits</span>(fdo) <span class="ot">&lt;-</span> <span class="fu">lm</span>(y2∼A∗B∗C, <span class="at">data =</span> fdo)</span>
<span id="cb119-3"><a href="qualitytools.html#cb119-3" tabindex="-1"></a><span class="fu">fits</span>(fdo)</span></code></pre></div>
<div class="inline-figure"><img src="graficos/multidfaclm.png" width="500"></div>
</div>
<div id="pasar-a-un-entorno-de-proceso-con-un-mayor-rendimiento-esperado" class="section level3" number="5.4.5">
<h3>
<span class="header-section-number">5.4.5</span> Pasar a un entorno de proceso con un mayor rendimiento esperado<a class="anchor" aria-label="anchor" href="#pasar-a-un-entorno-de-proceso-con-un-mayor-rendimiento-esperado"><i class="fas fa-link"></i></a>
</h3>
<p>Como el proceso puede ser modelado por una relación lineal se puede determinar un alto rendimiento fácilmente, esto se puede calcular gráficamente o utilizando el método <code>steepAscent</code>:</p>
<div class="sourceCode" id="cb120"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sao</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/steepAscent.html">steepAscent</a></span><span class="op">(</span>factors <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"A"</span>, <span class="st">"B"</span><span class="op">)</span>, response <span class="op">=</span> <span class="st">"yield"</span>, data <span class="op">=</span> <span class="va">dfac</span>, steps <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/renddfac1.png" width="300"></div>
<div class="sourceCode" id="cb121"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sao</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/renddfac2.png" width="300"></div>
<p>Como se estableció los valores reales anteriormente con los métodos <code>highs</code> y <code>lows</code> son mostrados como valores reales. Los valores de respuesta de <code>sao</code> pueden ser establecidos con el método <code>response</code> y graficados con <code>plot</code></p>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">predicted</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="va">sao</span><span class="op">[</span>,<span class="fl">5</span><span class="op">]</span>, <span class="va">sao</span><span class="op">[</span>,<span class="fl">6</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu">responde</span><span class="op">(</span><span class="va">sao</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">predicted</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">sao</span>, type<span class="op">=</span><span class="st">'b'</span>, col<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="diseños-de-superficies-de-respuesta" class="section level3" number="5.4.6">
<h3>
<span class="header-section-number">5.4.6</span> Diseños de superficies de respuesta<a class="anchor" aria-label="anchor" href="#dise%C3%B1os-de-superficies-de-respuesta"><i class="fas fa-link"></i></a>
</h3>
<p>Se debe tener en cuenta que no todas las relaciones son lineales por lo cual para detectar y modelizar las relaciones no lineales se necesitan más de dos combinaciones por factor. Para averiguar si un diseño de superficie de respuesta es necesario (es decir, un diseño con más de dos combinaciones por factor) se puede
comparar el valor esperado de la(s) variable(s) de respuesta con la(s) observada(s) utilizando
puntos centrales . Cuanto mayor sea la diferencia entre los valores
esperados, más improbable será que esta diferencia sea el resultado de ruido aleatorio.
Bajo el contexto del ejercicio desarrollado en la sección de diseño factorial <span class="math inline">\(2^{k}\)</span> utilizamos el método <strong>steepAscent</strong> de qualityTools para pasar a una mejor región del proceso. El centro de la
nueva región de proceso está definido por 144 y 165 en valores reales la cual es el inicio del nuevo diseño.</p>
<div class="sourceCode" id="cb123"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#Semilla</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">fdo2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/facDesign.html">facDesign</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">2</span>, centerCube <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">fdo2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Factor1"</span>, <span class="st">"Factor2"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/lows-methods.html">lows</a></span><span class="op">(</span><span class="va">fdo2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">13</span>, <span class="fl">4</span>, <span class="fl">155</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/highs-methods.html">highs</a></span><span class="op">(</span><span class="va">fdo2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">15</span>, <span class="fl">5</span>, <span class="fl">175</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/dario.jpg" width="700"></div>
<p>el rendimiento se obtiene utilizando el <code>simProc</code> y se asigna al nuevo diseño con la
ayuda del método genérico de <code>response</code> del paquete <strong>qualityTools</strong></p>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rendimiento</span><span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">134</span>,<span class="fl">175</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">144.5</span>,<span class="fl">165.5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">155</span>,<span class="fl">155</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">144.5</span>,<span class="fl">165.5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">155</span>,<span class="fl">175</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">144.5</span>,<span class="fl">165.5</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">134</span>,<span class="fl">155</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/response-methods.html">response</a></span><span class="op">(</span><span class="va">fdo2</span><span class="op">)</span><span class="op">=</span><span class="va">rendimiento</span></span></code></pre></div>
<p>Si se observan los gráficos de residuos, se apreciará una diferencia sustancial entre los valores esperados
y los valores observados (podría realizarse una prueba de falta de ajuste para verificarlo).
Para llegar a un modelo que describa la relación hay que añadir más puntos
que se denominan la <strong>starportion</strong> del diseño de la superficie de respuesta.
La adición de la <strong>starportion</strong> se realiza fácilmente utilizando el método <code>starDesign</code> del paquete <strong>qualityTools</strong>
Por defecto, el valor de alfa se elige de forma que ambos criterios, ortogonalidad y
rotatabilidad se cumplan . Se llama al método starDesign en el objeto de diseño factorial
factorial <code>fdo2</code>. La llamada a <code>rsdo</code> le mostrará el diseño de superficie de respuesta resultante.Debe tener una porción cúbica que conste de 4 runs, 3 puntos centrales en la porción cúbica, 4
axiales y 3 puntos centrales en la porción de estrella (<strong>starportion</strong>).</p>
<div class="sourceCode" id="cb125"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rsdo</span><span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/starDesign.html">starDesign</a></span><span class="op">(</span> data <span class="op">=</span><span class="va">fdo2</span> <span class="op">)</span></span>
<span><span class="va">rsdo</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th>StandOrd</th>
<th>RunOrder</th>
<th>Block</th>
<th>A</th>
<th>B</th>
<th>rendimiento</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>3</td>
<td>1</td>
<td>1</td>
<td>-1.000</td>
<td>3769</td>
</tr>
<tr class="even">
<td>7</td>
<td>7</td>
<td>2</td>
<td>1</td>
<td>0.000</td>
<td>7953</td>
</tr>
<tr class="odd">
<td>2</td>
<td>2</td>
<td>3</td>
<td>1</td>
<td>-1.000</td>
<td>7935</td>
</tr>
<tr class="even">
<td>6</td>
<td>6</td>
<td>4</td>
<td>1</td>
<td>0.000</td>
<td>7865</td>
</tr>
<tr class="odd">
<td>4</td>
<td>4</td>
<td>5</td>
<td>1</td>
<td>1.000</td>
<td>NA</td>
</tr>
<tr class="even">
<td>5</td>
<td>5</td>
<td>6</td>
<td>1</td>
<td>0.000</td>
<td>NA</td>
</tr>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>7</td>
<td>1</td>
<td>-1.000</td>
<td>NA</td>
</tr>
<tr class="even">
<td>8</td>
<td>8</td>
<td>8</td>
<td>2</td>
<td>-1.414</td>
<td>NA</td>
</tr>
<tr class="odd">
<td>9</td>
<td>9</td>
<td>9</td>
<td>2</td>
<td>1.000</td>
<td>NA</td>
</tr>
<tr class="even">
<td>10</td>
<td>10</td>
<td>10</td>
<td>2</td>
<td>0.000</td>
<td>NA</td>
</tr>
<tr class="odd">
<td>11</td>
<td>11</td>
<td>11</td>
<td>2</td>
<td>0.000</td>
<td>NA</td>
</tr>
<tr class="even">
<td>12</td>
<td>12</td>
<td>12</td>
<td>2</td>
<td>0.000</td>
<td>NA</td>
</tr>
<tr class="odd">
<td>13</td>
<td>13</td>
<td>13</td>
<td>2</td>
<td>0.000</td>
<td>NA</td>
</tr>
<tr class="even">
<td>14</td>
<td>14</td>
<td>14</td>
<td>2</td>
<td>0.000</td>
<td>NA</td>
</tr>
</tbody>
</table></div>
<p>Utilizando el método estrella del paquete <strong>qualityTools</strong> se pueden ensamblar fácilmente diseños
secuencialmente. Esta estrategia secuencial ahorra recursos pues, en comparación con empezar con
diseño de superficie de respuesta desde el principio, la parte en estrella sólo se ejecuta si es realmente necesaria. Los rendimientos del proceso siguen estando dados por el método <code>simProc</code>.</p>
<div class="sourceCode" id="cb126"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">yield2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="va">yield</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">130</span>, <span class="fl">165</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">155</span>, <span class="fl">165</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">144</span>, <span class="fl">155</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">144</span>, <span class="fl">179</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">144</span>, <span class="fl">165</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">144</span>, <span class="fl">165</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/simProc.html">simProc</a></span><span class="op">(</span><span class="fl">144</span>, <span class="fl">165</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/response-methods.html">response</a></span><span class="op">(</span><span class="va">rsdo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">yield2</span></span></code></pre></div>
<p>Se ajusta un modelo cuadrático completo utilizando el método <strong>lm</strong></p>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lm.3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">yield2</span> <span class="op">~</span> <span class="va">A</span><span class="op">*</span><span class="va">B</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">A</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">B</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">rsdo</span><span class="op">)</span></span></code></pre></div>
<p>La superficie de respuesta puede visualizarse utilizando <code>wirePlot</code> y <code>contourPlot</code>.</p>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/wirePlot.html">wirePlot</a></span><span class="op">(</span><span class="va">A</span>, <span class="va">B</span>, <span class="va">yield2</span>, form <span class="op">=</span> <span class="st">"yield2 ~ A*B + I(A^2) + I(B^2)"</span>, data <span class="op">=</span> <span class="va">rsdo</span>, theta <span class="op">=</span> <span class="op">-</span><span class="fl">70</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/contourPlot.html">contourPlot</a></span><span class="op">(</span><span class="va">A</span>, <span class="va">B</span>, <span class="va">yield2</span>, form <span class="op">=</span> <span class="st">"yield2 ~ A*B + I(A^2) + I(B^2)"</span>, data <span class="op">=</span> <span class="va">rsdo</span><span class="op">)</span></span></code></pre></div>
<p><img src="graficos/dario1.jpg" width="700"><img src="graficos/dario2.jpg" width="700"></p>
<p>Se compara los resultados de los diseños factorial y de superficie de respuesta con el proceso simulado.</p>
<p>Se pueden crear diseños de superficie de respuesta utilizando el método <code>rsmDesign</code>. Por ejemplo un diseño con alfa = 1.633, 0 puntos centrales en la parte del cubo y 6 puntos centrales en la parte de la estrella con:</p>
<div class="sourceCode" id="cb129"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fdo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/rsmDesign.html">rsmDesign</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">3</span>, alpha <span class="op">=</span> <span class="fl">1.633</span>, cc <span class="op">=</span> <span class="fl">0</span>, cs <span class="op">=</span> <span class="fl">6</span><span class="op">)</span></span></code></pre></div>
<p>y el diseño se puede poner en orden estándar utilizando el método <code>randomize</code> con el argumento <code>so=TRUE</code> (es decir, orden estándar). <code>cc</code> significa centerCube y <code>cs</code> para centerStar.</p>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fdo</span> <span class="op">&lt;-</span> <span class="fu">randomizeDesign</span><span class="op">(</span><span class="va">fdo</span>, so <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<p>Los diseños de superficie de respuesta también pueden elegirse a partir de una tabla utilizando el método <code>rsmChoose</code>.</p>
<div class="sourceCode" id="cb131"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">rsdo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/rsmDesign.html">rsmDesign</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div id="montaje-secuencial-de-diseños-de-superficie-de-respuesta" class="section level4" number="5.4.6.1">
<h4>
<span class="header-section-number">5.4.6.1</span> Montaje secuencial de diseños de superficie de respuesta<a class="anchor" aria-label="anchor" href="#montaje-secuencial-de-dise%C3%B1os-de-superficie-de-respuesta"><i class="fas fa-link"></i></a>
</h4>
<p>El ensamblaje secuencial es una característica importante de los diseños de superficie de respuesta. En función de de las características del diseño factorial (fraccional) puede aumentarse una porción de estrella utilizando el método <code>starDesign</code>. Una porción en estrella consta de recorridos axiales
y puntos centrales opcionales (<code>cs</code>) en la parte axial a diferencia de los puntos centrales (<code>cc</code>) en la parteparte cúbica.</p>
<div class="sourceCode" id="cb132"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fdo3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/facDesign.html">facDesign</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">6</span><span class="op">)</span></span>
<span><span class="va">rsdo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/starDesign.html">starDesign</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="st">"orthogonal"</span>, data <span class="op">=</span> <span class="va">fdo3</span><span class="op">)</span></span></code></pre></div>
<p>En caso de que no se entregue ningún diseño factorial (fraccional) al método <code>starDesign</code>, se devuelve una lista con <code>data.frames</code> que pueden asignarse al diseño factorial (fraccional) existente utilizando los métodos <code>star</code>, <code>centerStar</code> y <code>centerCube</code>.</p>
<div class="inline-figure"><img src="graficos/dario3.jpg" width="700"></div>
</div>
<div id="aleatorización" class="section level4" number="5.4.6.2">
<h4>
<span class="header-section-number">5.4.6.2</span> Aleatorización<a class="anchor" aria-label="anchor" href="#aleatorizaci%C3%B3n"><i class="fas fa-link"></i></a>
</h4>
<p>La aleatorización se consigue utilizando el método <code>randomize</code>.
Es necesario suministrar una semilla aleatoria (random.seed) que es útil para tener el mismo orden de ejecución en cualquier máquina.</p>
<div class="sourceCode" id="cb133"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/randomize.html">randomize</a></span><span class="op">(</span><span class="va">fdo</span>, random.seed <span class="op">=</span> <span class="fl">123</span><span class="op">)</span></span></code></pre></div>
<p>El método <code>randomize</code> se puede utilizar para obtener un diseño en orden estándar con la ayuda del argumento <code>so</code>.</p>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">randomizeDesign</span><span class="op">(</span><span class="va">fdo</span>, so <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="bloqueo" class="section level4" number="5.4.6.3">
<h4>
<span class="header-section-number">5.4.6.3</span> Bloqueo<a class="anchor" aria-label="anchor" href="#bloqueo"><i class="fas fa-link"></i></a>
</h4>
<p>El bloqueo es otra característica relevante y puede conseguirse mediante el método de <code>blocking</code>. Bloquear un diseño a posteriori no siempre tiene éxito.
Sin embargo, no es problemático durante el montaje secuencial.</p>
</div>
</div>
<div id="deseabilidades" class="section level3" number="5.4.7">
<h3>
<span class="header-section-number">5.4.7</span> Deseabilidades<a class="anchor" aria-label="anchor" href="#deseabilidades"><i class="fas fa-link"></i></a>
</h3>
<p>Muchos problemas requieren optimización simultánea de más de una variable de respuesta. La optimización puede lograrse maximizando o minimizando el valor de la respuesta o tratando de situar la respuesta en un objetivo específico.En la Optimización mediante el enfoque de las deseabilidades Derringer y Suich [1980], los valores (predichos) de las variables de respuesta se transforman en valores dentro del intervalo [0,1] utilizando tres métodos de deseabilidad diferentes
para los tres criterios de optimización diferentes (es decir, minimizar, maximizar, objetivo). A cada valor de una variable de respuesta se le puede asignar una deseabilidad específica, optimizando más de una variable de respuesta. La media geométrica de las deseabilidades específicas caracteriza la deseabilidad global.</p>
<p><span class="math display">\[\sqrt[n]{\prod^n_{i=1}d_i}\]</span></p>
<p>Para los valores previstos de las respuestas, cada combinación de factores tiene una correspondiente deseabilidad específica y se puede calcular una deseabilidad global. Supongamos que tenemos
tres respuestas. Para un ajuste específico de los factores, las respuestas tienen deseabilidades
como <span class="math inline">\(d1 = 0,7\)</span> para <span class="math inline">\(y1, d2 = 0,8\)</span> para <span class="math inline">\(y2\)</span> y <span class="math inline">\(d3 = 0,2\)</span> para <span class="math inline">\(y3\)</span>. La deseabilidad global
viene dada por la media geométrica.</p>
<p><span class="math display">\[d_{all}=\sqrt[n]{d_1d_2\ldots d_n}\]</span>
<span class="math display">\[=\sqrt[3]{d_1d_2\ldots d_n}\]</span>
<span class="math display">\[=\sqrt[n]{0.7\cdot0.8\cdot0.2}\]</span></p>
<p>Los métodos de deseabilidad pueden definirse mediante el método <code>desires</code>. La dirección de optimización de cada variable de respuesta se define mediante los argumentos <code>min</code>,<code>max</code> y <code>target</code> del método <code>desires</code>. El argumento <code>target</code> se establece con <code>max</code> para la maximización, <code>min</code> para la minimización y un valor específico para la optimización hacia un objetivo concreto. De esta constelación surgen tres ajustes:</p>
<p><strong>target = max:</strong> min es el valor mínimo aceptable. Si la variable de respuesta toma valores por debajo de min, la deseabilidad correspondiente será cero. Para valores iguales o mayores que min, la deseabilidad será mayor que cero.</p>
<p><strong>target = min:</strong> max es el valor máximo aceptable. Si la variable de respuesta toma valores por encima de max, la deseabilidad correspondiente será cero. Para valores iguales o menores que max, la deseabilidad será mayor que cero.</p>
<p><strong>target = valor:</strong> una variable de respuesta con un valor de valor se relaciona con la deseabilidad más alta alcanzable de 1. Los valores fuera de min o max llevan a una deseabilidad de cero, dentro de min y max a valores dentro de (0,1].</p>
<div class="sourceCode" id="cb135"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#EJEMPLO:</span></span>
<span></span>
<span><span class="va">d1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/desirability.html">desirability</a></span><span class="op">(</span><span class="va">y1</span>, <span class="fl">120</span>, <span class="fl">170</span>, scale <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>, target <span class="op">=</span> <span class="st">"max"</span><span class="op">)</span></span>
<span><span class="va">d3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/desirability.html">desirability</a></span><span class="op">(</span><span class="va">y3</span>, <span class="fl">400</span>, <span class="fl">600</span>, target <span class="op">=</span> <span class="fl">500</span><span class="op">)</span></span>
<span><span class="va">d1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">d1</span>, col <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">d3</span>, col <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="utilización-de-deseabilidades-junto-con-experimentos-diseñados" class="section level3" number="5.4.8">
<h3>
<span class="header-section-number">5.4.8</span> Utilización de deseabilidades junto con experimentos diseñados<a class="anchor" aria-label="anchor" href="#utilizaci%C3%B3n-de-deseabilidades-junto-con-experimentos-dise%C3%B1ados"><i class="fas fa-link"></i></a>
</h3>
<p>La metodología de la deseabilidad se apoya en los objetos de diseño factorial. El resultado
del método de deseabilidad puede almacenarse en el objeto de diseño, de modo que la información que
pertenece a cada uno se almacena en el mismo lugar (es decir, el propio diseño).</p>
<p><strong>Experimento</strong>
Los datos utilizados proceden de Derringer y Suich [1980]. Se definieron cuatro respuestas <span class="math inline">\(y_1, y_2, y_3\)</span> e <span class="math inline">\(y_4\)</span>.
Los factores utilizados en este experimento fueron la sílicio, el silano y el azufre con ajustes de factor alto de <span class="math inline">\(1,7, 60, 2,8\)</span> y factores bajos de <span class="math inline">\(0,7, 40, 1,8\)</span>. Se desea maximizar <span class="math inline">\(y_1\)</span> e <span class="math inline">\(y_2\)</span>
e <span class="math inline">\(y_3\)</span> e <span class="math inline">\(y_4\)</span> fijados en un objetivo específico.
En primer lugar, se crea el diseño correspondiente y a continuación, utilizamos el método <code>randomize</code> para obtener el orden estándar del diseño.</p>
<div class="sourceCode" id="cb136"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ddo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/rsmDesign.html">rsmDesign</a></span><span class="op">(</span>k <span class="op">=</span> <span class="fl">3</span>, alpha <span class="op">=</span> <span class="fl">1.633</span>, cc <span class="op">=</span> <span class="fl">0</span>, cs <span class="op">=</span> <span class="fl">6</span><span class="op">)</span></span>
<span><span class="va">ddo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/randomize.html">randomize</a></span><span class="op">(</span><span class="va">ddo</span>, so <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Opcional</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"silica"</span>, <span class="st">"silan"</span>, <span class="st">"sulfur"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Opcional</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/highs-methods.html">highs</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1.7</span>, <span class="fl">60</span>, <span class="fl">2.8</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Opcional</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/lows-methods.html">lows</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.7</span>, <span class="fl">40</span>, <span class="fl">1.8</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#</span></span>
<span></span>
<span><span class="va">y1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">102</span>, <span class="fl">120</span>, <span class="fl">117</span>, <span class="fl">198</span>, <span class="fl">103</span>, <span class="fl">132</span>, <span class="fl">132</span>, <span class="fl">139</span>, <span class="fl">102</span>, <span class="fl">154</span>, <span class="fl">96</span>, <span class="fl">163</span>, <span class="fl">116</span>, <span class="fl">153</span>, <span class="fl">133</span>, <span class="fl">133</span>, <span class="fl">140</span>, <span class="fl">142</span>, <span class="fl">145</span>, <span class="fl">142</span><span class="op">)</span></span>
<span><span class="va">y2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">900</span>, <span class="fl">860</span>, <span class="fl">800</span>, <span class="fl">2294</span>, <span class="fl">490</span>, <span class="fl">1289</span>, <span class="fl">1270</span>, <span class="fl">1090</span>, <span class="fl">770</span>, <span class="fl">1690</span>, <span class="fl">700</span>, <span class="fl">1540</span>, <span class="fl">2184</span>, <span class="fl">1784</span>, <span class="fl">1300</span>, <span class="fl">1300</span>, <span class="fl">1145</span>, <span class="fl">1090</span>, <span class="fl">1260</span>, <span class="fl">1344</span><span class="op">)</span></span>
<span><span class="va">y3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">470</span>, <span class="fl">410</span>, <span class="fl">570</span>, <span class="fl">240</span>, <span class="fl">640</span>, <span class="fl">270</span>, <span class="fl">410</span>, <span class="fl">380</span>, <span class="fl">590</span>, <span class="fl">260</span>, <span class="fl">520</span>, <span class="fl">380</span>, <span class="fl">520</span>, <span class="fl">290</span>, <span class="fl">380</span>, <span class="fl">380</span>, <span class="fl">430</span>, <span class="fl">430</span>, <span class="fl">390</span>, <span class="fl">390</span><span class="op">)</span></span>
<span><span class="va">y4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">67.5</span>, <span class="fl">65</span>, <span class="fl">77.5</span>, <span class="fl">74.5</span>, <span class="fl">62.5</span>, <span class="fl">67</span>, <span class="fl">78</span>, <span class="fl">70</span>, <span class="fl">76</span>, <span class="fl">70</span>, <span class="fl">63</span>, <span class="fl">75</span>, <span class="fl">65</span>, <span class="fl">71</span>, <span class="fl">70</span>, <span class="fl">68.5</span>, <span class="fl">68</span>, <span class="fl">68</span>, <span class="fl">69</span>, <span class="fl">70</span><span class="op">)</span></span></code></pre></div>
<p>El <code>data.frame</code> ordenado de estas 4 respuestas se asigna al objeto de diseño <code>ddo</code>.</p>
<div class="sourceCode" id="cb137"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/response-methods.html">response</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">y1</span>, <span class="va">y2</span>, <span class="va">y3</span>, <span class="va">y4</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">8</span>, <span class="fl">1</span>, <span class="fl">6</span>, <span class="fl">7</span>, <span class="fl">4</span>, <span class="fl">9</span><span class="op">:</span><span class="fl">20</span><span class="op">)</span>, <span class="op">]</span></span></code></pre></div>
<p>Las deseabilidades se incorporan con el método <code>desires</code> .
Ya se han definido <span class="math inline">\(y_1\)</span> e <span class="math inline">\(y_3\)</span>, por lo que quedan por definir las deseabilidades de <span class="math inline">\(y_2\)</span> e <span class="math inline">\(y_4\)</span>.</p>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">d2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/desirability.html">desirability</a></span><span class="op">(</span><span class="va">y2</span>, <span class="fl">1000</span>, <span class="fl">1300</span>, target <span class="op">=</span> <span class="st">"max"</span><span class="op">)</span></span>
<span><span class="va">d4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/desirability.html">desirability</a></span><span class="op">(</span><span class="va">y4</span>, <span class="fl">60</span>, <span class="fl">75</span>, target <span class="op">=</span> <span class="fl">67.5</span><span class="op">)</span></span></code></pre></div>
<p>Es necesario definir las deseabilidades con los nombres de las variables de respuesta para poder utilizarlas con el objeto de diseño. El método de los deseos se utiliza del siguiente modo</p>
<div class="sourceCode" id="cb139"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/desires-methods.html">desires</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">d1</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/desires-methods.html">desires</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">d2</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/desires-methods.html">desires</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">d3</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/desires-methods.html">desires</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">d4</span></span></code></pre></div>
<p>Los ajustes se establecen como en Derringer y Suich [1980] utilizando los métodos de ajuste del paquete qualityTools de calidad.</p>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/fits-methods.html">fits</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y1</span> <span class="op">~</span> <span class="va">A</span> <span class="op">+</span> <span class="va">B</span> <span class="op">+</span> <span class="va">C</span> <span class="op">+</span> <span class="va">A</span><span class="op">:</span><span class="va">B</span> <span class="op">+</span> <span class="va">A</span><span class="op">:</span><span class="va">C</span> <span class="op">+</span> <span class="va">B</span><span class="op">:</span><span class="va">C</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">A</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">B</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">C</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">ddo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/fits-methods.html">fits</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y2</span> <span class="op">~</span> <span class="va">A</span> <span class="op">+</span> <span class="va">B</span> <span class="op">+</span> <span class="va">C</span> <span class="op">+</span> <span class="va">A</span><span class="op">:</span><span class="va">B</span> <span class="op">+</span> <span class="va">A</span><span class="op">:</span><span class="va">C</span> <span class="op">+</span> <span class="va">B</span><span class="op">:</span><span class="va">C</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">A</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">B</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">C</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">ddo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/fits-methods.html">fits</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y3</span> <span class="op">~</span> <span class="va">A</span> <span class="op">+</span> <span class="va">B</span> <span class="op">+</span> <span class="va">C</span> <span class="op">+</span> <span class="va">A</span><span class="op">:</span><span class="va">B</span> <span class="op">+</span> <span class="va">A</span><span class="op">:</span><span class="va">C</span> <span class="op">+</span> <span class="va">B</span><span class="op">:</span><span class="va">C</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">A</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">B</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">C</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">ddo</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/fits-methods.html">fits</a></span><span class="op">(</span><span class="va">ddo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y4</span> <span class="op">~</span> <span class="va">A</span> <span class="op">+</span> <span class="va">B</span> <span class="op">+</span> <span class="va">C</span> <span class="op">+</span> <span class="va">A</span><span class="op">:</span><span class="va">B</span> <span class="op">+</span> <span class="va">A</span><span class="op">:</span><span class="va">C</span> <span class="op">+</span> <span class="va">B</span><span class="op">:</span><span class="va">C</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">A</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">B</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">C</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">ddo</span><span class="op">)</span></span></code></pre></div>
<p>Finalmente se tiene que</p>
<div class="sourceCode" id="cb141"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/optimum.html">optimum</a></span><span class="op">(</span><span class="va">ddo</span>, type <span class="op">=</span> <span class="st">"optim"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="graficos/dario4.jpg" width="700"></div>
</div>
<div id="diseños-de-mezclas" class="section level3" number="5.4.9">
<h3>
<span class="header-section-number">5.4.9</span> Diseños de mezclas<a class="anchor" aria-label="anchor" href="#dise%C3%B1os-de-mezclas"><i class="fas fa-link"></i></a>
</h3>
<p>La generación de los diferentes tipos de diseños de mezcla es totalmente compatible
incluyendo un contorno ternario y un gráfico 3D. El análisis de estos diseños debe realizarse sin ningún soporte específico mediante un método del paquete <code>qualityTools</code>.
El método mixDesign puede utilizarse, por ejemplo, para crear diseños de celosía simplex y diseños de centroide simplex.
Los métodos genéricos <code>response</code>, <code>names</code>, <code>highs</code>, <code>lows</code>, <code>units</code> y <code>types</code> vuelven a estar presentes.
Un conjunto de datos Cornell [op. 2002] viene dado por el alargamiento del hilo para varias mezclas de tres factores. Este ejemplo puede reconstruirse utilizando el método <code>mixDesign</code>.</p>
<div class="sourceCode" id="cb142"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#EJEMPLO </span></span>
<span></span>
<span><span class="va">mdo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/mixDesign.html">mixDesign</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">2</span>, center <span class="op">=</span> <span class="cn">FALSE</span>, axial <span class="op">=</span> <span class="cn">FALSE</span>, randomize <span class="op">=</span> <span class="cn">FALSE</span>, replicates <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Warning in `[&lt;-`(`*tmp*`, i, value = new("doeFactor")): implicit list embedding
## of S4 objects is deprecated

## Warning in `[&lt;-`(`*tmp*`, i, value = new("doeFactor")): implicit list embedding
## of S4 objects is deprecated

## Warning in `[&lt;-`(`*tmp*`, i, value = new("doeFactor")): implicit list embedding
## of S4 objects is deprecated</code></pre>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">mdo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"polyethylene"</span>, <span class="st">"polystyrene"</span>, <span class="st">"polypropylene"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Establecer respuesta (es decir, elongación del hilo)</span></span>
<span><span class="va">elongation</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">11.0</span>, <span class="fl">12.4</span>, <span class="fl">15.0</span>, <span class="fl">14.8</span>, <span class="fl">16.1</span>, <span class="fl">17.7</span>, <span class="fl">16.4</span>, <span class="fl">16.6</span>, <span class="fl">8.8</span>, <span class="fl">10.0</span>, <span class="fl">10.0</span>, <span class="fl">9.7</span>, <span class="fl">11.8</span>, <span class="fl">16.8</span>, <span class="fl">16.0</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/response-methods.html">response</a></span><span class="op">(</span><span class="va">mdo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">elongation</span></span></code></pre></div>
<pre><code>## [1] "elongation"</code></pre>
<div class="sourceCode" id="cb146"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mdo</span></span></code></pre></div>
<pre><code>##    StandOrder RunOrder    Type   A   B   C elongation
## 1           1        1 1-blend 1.0 0.0 0.0       11.0
## 2           2        2 1-blend 1.0 0.0 0.0       12.4
## 3           3        3 2-blend 0.5 0.5 0.0       15.0
## 4           4        4 2-blend 0.5 0.5 0.0       14.8
## 5           5        5 2-blend 0.5 0.5 0.0       16.1
## 6           6        6 2-blend 0.5 0.0 0.5       17.7
## 7           7        7 2-blend 0.5 0.0 0.5       16.4
## 8           8        8 2-blend 0.5 0.0 0.5       16.6
## 9           9        9 1-blend 0.0 1.0 0.0        8.8
## 10         10       10 1-blend 0.0 1.0 0.0       10.0
## 11         11       11 2-blend 0.0 0.5 0.5       10.0
## 12         12       12 2-blend 0.0 0.5 0.5        9.7
## 13         13       13 2-blend 0.0 0.5 0.5       11.8
## 14         14       14 1-blend 0.0 0.0 1.0       16.8
## 15         15       15 1-blend 0.0 0.0 1.0       16.0</code></pre>
<div class="sourceCode" id="cb148"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/contourPlot3.html">contourPlot3</a></span><span class="op">(</span><span class="va">A</span>, <span class="va">B</span>, <span class="va">C</span>, <span class="va">elongation</span>, data <span class="op">=</span> <span class="va">mdo</span>, form <span class="op">=</span> <span class="st">"quadratic"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/wirePlot3.html">wirePlot3</a></span><span class="op">(</span><span class="va">A</span>, <span class="va">B</span>, <span class="va">C</span>, <span class="va">elongation</span>, data <span class="op">=</span> <span class="va">mdo</span>, form <span class="op">=</span> <span class="st">"quadratic"</span>, theta <span class="op">=</span> <span class="op">-</span><span class="fl">170</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-130-1.png" width="672"></div>
</div>
<div id="diseños-taguchi" class="section level3" number="5.4.10">
<h3>
<span class="header-section-number">5.4.10</span> Diseños Taguchi<a class="anchor" aria-label="anchor" href="#dise%C3%B1os-taguchi"><i class="fas fa-link"></i></a>
</h3>
<p>Los diseños Taguchi están disponibles utilizando el método <code>taguchiDesign</code>.</p>
<p>Hay dos tipos de diseños taguchi:</p>
<ul>
<li>Nivel único: todos los factores tienen el mismo número de niveles (por ejemplo, dos niveles para un L4_2).</li>
<li>Nivel mixto: los factores tienen diferentes números de niveles (por ejemplo, dos y tres niveles para un L18_2_3).</li>
</ul>
<p>Sin embargo, la mayoría de los diseños que se popularizaron como diseños Taguchi son factoriales fraccionados <span class="math inline">\(2^k\)</span> con una resolución muy baja de III (es decir, los efectos principales se confunden con interacciones de dos factores) u otros diseños de nivel mixto.
Se puede crear un diseño utilizando el método <code>taguchiDesign</code>. Los nombres de métodos genéricos, unidades, valores, resumen, trazado, lm y otros métodos se pueden utilizar.</p>
<div class="sourceCode" id="cb149"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#EJEMPLO</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">tdo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/taguchiDesign.html">taguchiDesign</a></span><span class="op">(</span><span class="st">"L9_3"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Warning in `[&lt;-`(`*tmp*`, i, value = new("taguchiFactor")): implicit list
## embedding of S4 objects is deprecated

## Warning in `[&lt;-`(`*tmp*`, i, value = new("taguchiFactor")): implicit list
## embedding of S4 objects is deprecated

## Warning in `[&lt;-`(`*tmp*`, i, value = new("taguchiFactor")): implicit list
## embedding of S4 objects is deprecated

## Warning in `[&lt;-`(`*tmp*`, i, value = new("taguchiFactor")): implicit list
## embedding of S4 objects is deprecated</code></pre>
<div class="sourceCode" id="cb151"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/values-methods.html">values</a></span><span class="op">(</span><span class="va">tdo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>A <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">20</span>, <span class="fl">40</span>, <span class="fl">60</span><span class="op">)</span>, B <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"material 1"</span>, <span class="st">"material 2"</span>, <span class="st">"material 3"</span><span class="op">)</span>, C <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">tdo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Factor 1"</span>, <span class="st">"Factor 2"</span>, <span class="st">"Factor 3"</span>, <span class="st">"Factor 4"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">tdo</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Taguchi SINGLE Design
## Information about the factors:
## 
##                A          B        C        D
## value 1       20 material 1        1        1
## value 2       40 material 2        2        2
## value 3       60 material 3        3        3
## name    Factor 1   Factor 2 Factor 3 Factor 4
## unit                                         
## type     numeric    numeric  numeric  numeric
## 
## -----------
## 
##   StandOrder RunOrder Replicate A B C D  y
## 1          4        1         1 2 1 2 3 NA
## 2          6        2         1 2 3 1 2 NA
## 3          9        3         1 3 3 2 1 NA
## 4          3        4         1 1 3 3 3 NA
## 5          2        5         1 1 2 2 2 NA
## 6          1        6         1 1 1 1 1 NA
## 7          7        7         1 3 1 3 2 NA
## 8          5        8         1 2 2 3 1 NA
## 9          8        9         1 3 2 1 3 NA
## 
## -----------</code></pre>
<p>El método <code>response</code> se utiliza para asignar los valores de las variables de respuesta. <code>effectPlot</code>
puede utilizarse una vez más para visualizar los tamaños del efecto de los factores</p>
<div class="sourceCode" id="cb153"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/response-methods.html">response</a></span><span class="op">(</span><span class="va">tdo</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">9</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/qualityTools/man/effectPlot.html">effectPlot</a></span><span class="op">(</span><span class="va">tdo</span>, col <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<p><img src="Libro_TidyQualityTools_files/figure-html/unnamed-chunk-132-1.png" width="672">
Como extra es importante el uso del comando <code>sessionInfo</code> con el fin de obtener el número de versión de R y los paquetes cargados :</p>
<div class="sourceCode" id="cb154"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## R version 4.3.2 (2023-10-31 ucrt)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 11 x64 (build 22631)
## 
## Matrix products: default
## 
## 
## locale:
## [1] LC_COLLATE=Spanish_Ecuador.utf8  LC_CTYPE=Spanish_Ecuador.utf8   
## [3] LC_MONETARY=Spanish_Ecuador.utf8 LC_NUMERIC=C                    
## [5] LC_TIME=Spanish_Ecuador.utf8    
## 
## time zone: America/Guayaquil
## tzcode source: internal
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] qualityTools_1.55          MASS_7.3-60               
##  [3] Rsolnp_1.16                tidyquant_1.0.7           
##  [5] quantmod_0.4.25            TTR_0.24.4                
##  [7] PerformanceAnalytics_2.0.4 xts_0.13.1                
##  [9] zoo_1.8-12                 lubridate_1.9.3           
## [11] forcats_1.0.0              stringr_1.5.1             
## [13] dplyr_1.1.4                purrr_1.0.2               
## [15] readr_2.1.4                tidyr_1.3.0               
## [17] tibble_3.2.1               ggplot2_3.4.4             
## [19] tidyverse_2.0.0            R6_2.5.1                  
## [21] sloop_1.0.1               
## 
## loaded via a namespace (and not attached):
##  [1] tidyselect_1.2.0    timeDate_4022.108   farver_2.1.1       
##  [4] blob_1.2.4          fastmap_1.1.1       lazyeval_0.2.2     
##  [7] digest_0.6.33       rpart_4.1.21        timechange_0.2.0   
## [10] lifecycle_1.0.4     survival_3.5-7      RSQLite_2.3.5      
## [13] magrittr_2.0.3      compiler_4.3.2      rlang_1.1.2        
## [16] sass_0.4.7          tools_4.3.2         utf8_1.2.4         
## [19] yaml_2.3.7          data.table_1.14.8   knitr_1.45         
## [22] labeling_0.4.3      bit_4.0.5           curl_5.1.0         
## [25] xml2_1.3.5          withr_2.5.2         nnet_7.3-19        
## [28] grid_4.3.2          fansi_1.0.5         timetk_2.9.0       
## [31] colorspace_2.1-0    future_1.33.1       globals_0.16.2     
## [34] scales_1.2.1        cli_3.6.1           rmarkdown_2.25     
## [37] generics_0.1.3      rstudioapi_0.15.0   future.apply_1.11.1
## [40] httr_1.4.7          tzdb_0.4.0          DBI_1.2.2          
## [43] cachem_1.0.8        splines_4.3.2       parallel_4.3.2     
## [46] vctrs_0.6.4         hardhat_1.3.1       Matrix_1.6-1.1     
## [49] jsonlite_1.8.7      bookdown_0.37       hms_1.1.3          
## [52] bit64_4.0.5         listenv_0.9.1       gower_1.0.1        
## [55] jquerylib_0.1.4     recipes_1.0.9       parallelly_1.36.0  
## [58] glue_1.6.2          codetools_0.2-19    Quandl_2.11.0      
## [61] rsample_1.2.1       stringi_1.8.2       gtable_0.3.4       
## [64] quadprog_1.5-8      downlit_0.4.3       munsell_0.5.0      
## [67] furrr_0.3.1         pillar_1.9.0        htmltools_0.5.7    
## [70] ipred_0.9-14        truncnorm_1.0-9     lava_1.7.3         
## [73] evaluate_0.23       lattice_0.21-9      highr_0.10         
## [76] memoise_2.0.1       bslib_0.6.0         class_7.3-22       
## [79] Rcpp_1.0.11         nlme_3.1-163        prodlim_2023.08.28 
## [82] mgcv_1.9-0          xfun_0.41           fs_1.6.3           
## [85] pkgconfig_2.0.3</code></pre>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="tidyquant.html"><span class="header-section-number">4</span> TidyQuant</a></div>
<div class="next"><a href="cambio-de-funciones.html"><span class="header-section-number">6</span> Cambio de Funciones</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#qualitytools"><span class="header-section-number">5</span> QualityTools</a></li>
<li><a class="nav-link" href="#fase-1-definir"><span class="header-section-number">5.1</span> Fase 1: Definir</a></li>
<li>
<a class="nav-link" href="#fase-2-medir"><span class="header-section-number">5.2</span> Fase 2: Medir</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#capacidad-de-calibre---msa-tipo-i"><span class="header-section-number">5.2.1</span> Capacidad de calibre - MSA Tipo I</a></li>
<li><a class="nav-link" href="#repetibilidad-y-reproducibidad-del-calibre---msa-tipo-ii"><span class="header-section-number">5.2.2</span> Repetibilidad y reproducibidad del calibre - MSA Tipo II</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#fase-3-analizar"><span class="header-section-number">5.3</span> Fase 3: Analizar</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#capacidad-del-proceso"><span class="header-section-number">5.3.1</span> Capacidad del Proceso</a></li></ul>
</li>
<li>
<a class="nav-link" href="#fase-4-mejorar"><span class="header-section-number">5.4</span> Fase 4: Mejorar</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#dise%C3%B1os-factoriales-2k"><span class="header-section-number">5.4.1</span> Diseños factoriales \(2^{k}\)</a></li>
<li><a class="nav-link" href="#dise%C3%B1os-factoriales-fraccionarios-2k-p"><span class="header-section-number">5.4.2</span> Diseños factoriales fraccionarios \(2^{k-p}\)</a></li>
<li><a class="nav-link" href="#dise%C3%B1os-replicados-y-puntos-centrales"><span class="header-section-number">5.4.3</span> Diseños replicados y puntos centrales</a></li>
<li><a class="nav-link" href="#respuestas-m%C3%BAltiples"><span class="header-section-number">5.4.4</span> Respuestas múltiples</a></li>
<li><a class="nav-link" href="#pasar-a-un-entorno-de-proceso-con-un-mayor-rendimiento-esperado"><span class="header-section-number">5.4.5</span> Pasar a un entorno de proceso con un mayor rendimiento esperado</a></li>
<li><a class="nav-link" href="#dise%C3%B1os-de-superficies-de-respuesta"><span class="header-section-number">5.4.6</span> Diseños de superficies de respuesta</a></li>
<li><a class="nav-link" href="#deseabilidades"><span class="header-section-number">5.4.7</span> Deseabilidades</a></li>
<li><a class="nav-link" href="#utilizaci%C3%B3n-de-deseabilidades-junto-con-experimentos-dise%C3%B1ados"><span class="header-section-number">5.4.8</span> Utilización de deseabilidades junto con experimentos diseñados</a></li>
<li><a class="nav-link" href="#dise%C3%B1os-de-mezclas"><span class="header-section-number">5.4.9</span> Diseños de mezclas</a></li>
<li><a class="nav-link" href="#dise%C3%B1os-taguchi"><span class="header-section-number">5.4.10</span> Diseños Taguchi</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Integración del Paquete QualityTools con Tidyverse</strong>" was written by Miguel Flores, Andrea Barahona, Fabián Encarnación, Dario Quishpe. It was last built on 2024-04-26.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
